apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: hue
  name: hue
spec:
  type: NodePort
  ports:
  - name: "8888"
    port: 8888
    targetPort: 8088
  selector:
    io.kompose.service: hue
status:
  loadBalancer: {}
