apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: hue
  name: hue
spec:
  replicas: 1
  template:
    metadata:
      labels:
        io.kompose.service: hue
    spec:
      containers:
      - env:
        - name: NAMENODE_HOST
          value: namenode
        image: bde2020/hdfs-filebrowser:latest
        name: hue
        ports:
        - containerPort: 8088
        resources: {}
      restartPolicy: Always
