apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: nodemanager1
  name: nodemanager1
spec:
  serviceName: "nodemanager1"
  replicas: 1
  template:
    metadata:
      labels:
        io.kompose.service: nodemanager1
    spec:
      containers:
      - env:
        envFrom:
          - configMapRef:
              name: hadoop-env
        image: "{{ .Values.Nodemanager1.Image }}:{{ .Values.Nodemanager1.ImageTag }}"
        name: nodemanager1
        ports:
        - containerPort: 8042
        resources: {}
      restartPolicy: Always
