apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: resourcemanager
  name: resourcemanager
spec:
  type: NodePort
  ports:
  - name: "8088"
    port: 8088
    targetPort: 8088
  - name: "8031"
    port: 8031
    targetPort: 8031
  - name: "8032"
    port: 8032
    targetPort: 8032
  - name: "8033"
    port: 8033
    targetPort: 8033
  selector:
    io.kompose.service: resourcemanager
status:
  loadBalancer: {}
